JAGUARETEKAA/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from JAGUARETEKAA import views


urlpatterns =[
	path('', views.home, name="home"),
	path('categoria/<int:id>/', views.categoria, name="categoria"),
	path('altaproducto', views.altaproducto, name="altaproducto"),
	path('modificarproducto/<int:id>/', views.modificarproducto, name="modificarproducto"),
	path('eliminarproducto/<int:id>/', views.eliminarproducto, name="eliminarproducto"),
	path('buscarproducto', views.buscarproducto, name="buscarproducto"),
	path('detalleproducto/<int:id>', views.detalleproducto, name="detalleproducto"),
	path('listaproductos', views.listaproductos, name="listaproductos"),

	path('acercade/', views.acercade, name="acercade"),
	path('contacto/', views.contacto, name="contacto"),
	path('registro/', views.registro, name="registro"),
	path('carrito/', views.carrito, name="carrito"),

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PF/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JAGUARETEKAA.urls')),
    path('carrito/', include('carrito.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

carrito/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "carrito"

urlpatterns =[
	path("agregar_producto/<int:producto_id>/", views.agregar_producto, name="agregar_producto"),
	path("eliminar_producto/<int:producto_id>/", views.eliminar_producto, name="eliminar_producto"),
	path("restar_producto/<int:producto_id>/", views.restar_producto, name="restar_producto"),
	path("vaciar_carrito/", views.vaciar_carrito, name="vaciar_carrito"),
	#path('carrito/', views.carrito, name="carrito"),
]

JAGUARETEKAA/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
	descripcion=models.CharField(max_length=50)

	class Meta:
		verbose_name='Categoria'
		verbose_name_plural='Categorias'

	def __str__(self):
		return(self.descripcion)

class Producto(models.Model):
	titulo=models.CharField(max_length=50)
	imagen=models.ImageField(upload_to='JAGUARETEKAA', null=True, blank=True)
	descripcion=models.CharField(max_length=50)
	precio=models.DecimalField(max_digits=9, decimal_places=2)
	categorias=models.ManyToManyField(Categoria)
	#categorias=models.ForeignKey(Categoria, on_delete=models.CASCADE)

	class Meta:
		verbose_name='Producto'
		verbose_name_plural='Productos'

	def __str__(self):
		return(self.titulo)

carrito/models.py
from django.db import models

# Create your models here.

JAGUARETEKAA/forms.py
from django import forms
from .models import Producto, Categoria
from django.contrib.auth.forms import UserCreationForm

class ProductoForm(forms.ModelForm):
	class Meta:
		model = Producto
		fields = '__all__'


class CustomUserCreationForm(UserCreationForm):
	pass	

JAGUARETEKAA/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from .forms import ProductoForm, CustomUserCreationForm
from .models import Categoria, Producto

# Create your views here.
def home(request):
	return render(request, "JAGUARETEKAA/home.html")

def home(request):
	categoria=Categoria.objects.all()
	
	return render(request, "JAGUARETEKAA/home.html", {
		"productos": Producto.objects.all(),
		
		"primeros_tres_productos": Producto.objects.all().order_by('-id')[:3],
		#"primeros_tres_productos": Producto.objects.all()[0:3],
		"resto_productos": Producto.objects.all()[4:10],
		"categorias":categoria
		})


def categoria(request, id):
	categoria=Categoria.objects.all()
	categoriafiltro = Categoria.objects.get(id=id)
	productos=Producto.objects.filter(categorias=categoriafiltro)
	#print(productos)
	return render(request, "JAGUARETEKAA/categoria.html", {
		'categoriafiltro': categoriafiltro,
		'productosfiltro': productos,
		'categorias': categoria
	})

def altaproducto(request):
	categoria=Categoria.objects.all()
	if request.method == "POST":
		formulario = ProductoForm(data=request.POST, files=request.FILES)
		if formulario.is_valid():
			formulario.save()
		else:
			return render(request, "JAGUARETEKAA/altaproducto.html", {
				"categorias":categoria,
				'form': formulario
			})				

	return render(request, "JAGUARETEKAA/altaproducto.html", {
		"categorias":categoria,
		'form': ProductoForm()
		})	

def modificarproducto(request, id):
	categoria=Categoria.objects.all()
	producto = get_object_or_404(Producto, id=id)
	data = {
		'form': ProductoForm(instance=producto)
	}

	if request.method == "POST":
		formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
		if formulario.is_valid():
			formulario.save()
			return redirect(to="listaproductos")
		data["form"] = formulario

	return render(request, "JAGUARETEKAA/modificarproducto.html", {
		#data, 
		'form': ProductoForm(instance=producto),
		"categorias":categoria, 
		})

def eliminarproducto(request, id):
	producto = get_object_or_404(Producto, id=id)
	producto.delete()
	return redirect(to="listaproductos")

def buscarproducto(request):
	categoria=Categoria.objects.all()
	buscar = request.GET.get('buscar')
	buscarproductos = Producto.objects.filter(titulo__icontains=buscar) | Producto.objects.filter(descripcion__icontains=buscar)
	if buscarproductos.count()==0:
		cantidadproductos = 0
	else:
		cantidadproductos = buscarproductos.count()
	return render(request, "JAGUARETEKAA/buscarproducto.html", {
		"buscarproductos":buscarproductos,
		"buscar": buscar,
		"cantidadproductos": cantidadproductos,
		"categorias":categoria
	})

def detalleproducto(request, id):
	categoria=Categoria.objects.all()
	detalleproducto=Producto.objects.get(id=id)
	return render(request, "JAGUARETEKAA/detalleproducto.html", {
		"detalleproducto": detalleproducto,
		"categorias":categoria
	})


def listaproductos(request):
	categoria=Categoria.objects.all()
	
	listaproductos=Producto.objects.all()
	return render(request, "JAGUARETEKAA/listaproductos.html", {
		'listaproductos': listaproductos,
		'categorias': categoria
	})


def acercade(request):
	categoria=Categoria.objects.all()
	return render(request, "JAGUARETEKAA/acercade.html", {
		"categorias":categoria
		})

def contacto(request):
	categoria=Categoria.objects.all()
	#if request.method == "POST":
    	#subject=request.POST["asunto"]
    	#message=request.POST["mensaje"] + " " + request.POST["email"]
    	#return render(request, "gracias.html")
    # Aca va el mailto

	return render(request, "JAGUARETEKAA/contacto.html", {
		"categorias":categoria
		})


def registro(request):
	data = {
		'form': CustomUserCreationForm()
	}

	if request.method == 'POST':
		formulario = CustomUserCreationForm(data=request.POST)
		if formulario.is_valid():
			formulario.save()
			return redirect(to="home")
		data["form"] = formulario

	return render(request, 'registration/registro.html', data)

def carrito(request):
	categoria=Categoria.objects.all()
	return render(request, 'JAGUARETEKAA/carrito.html', {
		"categorias":categoria
	})

carrito/views.py
from django.shortcuts import render, redirect
from JAGUARETEKAA.models import Categoria, Producto
from .carrito import Carrito

def agregar_producto(request, producto_id):
	carrito = Carrito(request)
	producto = Producto.objects.get(id=producto_id)
	#print(producto.id)
	carrito.agregar_producto(producto=producto)

	return redirect("carrito")


def eliminar_producto(request, producto_id):
	carrito = Carrito(request)
	producto = Producto.objects.get(id=producto_id)

	carrito.eliminar_producto(producto=producto)
	
	return redirect("/")

def restar_producto(request, producto_id):
	carrito = Carrito(request)
	producto = Producto.objects.get(id=producto_id)

	carrito.restar_producto(producto=producto)
	
	return redirect("carrito")

def vaciar_carrito(request):
	carrito = Carrito(request)
	
	carrito.vaciar_carrito()
	return redirect("/") 

'''def carrito(request):
	categoria=Categoria.objects.all()
	return render(request, 'carrito/carrito.html', {
		"categorias":categoria
	})
'''

JAGUARETEKAA/templates/CARRITO/carrito.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}
<h2>Carrito</h2>
<table class="table table-borderd" style="color: white;">
  <thead>
    <tr>
      <th colspan="3" class="text-center">
        Llena el Carrito ;)
      </th>
    </tr>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Suma</th>
    </tr>
  </thead>


<tbody>
  {% if request.session.carrito.items %}
    {% for key, value in request.session.carrito.items %}
      <tr class="text-center">
        <td>{{ value.titulo }}</td>
        <td>{{ value.cantidad }}</td>
        <td>
          <a href="{% url 'carrito:agregar_producto' value.producto_id %}" class="btn btn-sm btn-warning">+</a>
        </td>
      
        <td>
          <a href="{% url 'carrito:restar_producto' value.producto_id %}" class="btn btn-sm btn-warning">-</a>
        </td>        
        <td>{{ value.precio }}</td>
      </tr>
    {% endfor %}
  {% else %}
    <tr>
      <td colspan="3"></td>
      <div class="alert alert-danger text-center">
        Sin productos
      </div>
    </tr>
  {% endif %}
</tbody>

<tfoot>
  <tr>
    <td colspan="3">
      Total: {{ importe_total_carrito }}
    </td>
  </tr>
</tfoot>
</table>
{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/acercade.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}
 <div class="container">
  <div class="row">
  	<div class="col">
  		<img src="{% static 'JAGUARETEKAA/img/ecommerce.png' %}">
  	</div>
  	<div class="col">
    	<p class="text-faded">En JAGUARETE KAA S.A.A nos esforzamos por
        Atraer: provoca que tu público ideal conozca tu empresa, por medio de contenidos adecuados a sus intereses. Además, crea formas de comunicación fáciles con las que se relaciona desde el primer momento.

        Interactuar: es tu oportunidad para conocer y centrarte en la necesidad de cada persona interesada, donde le ofreces soluciones relevantes y personalizadas.

        Deleitar: una vez que das la solución específica, conseguirás que el cliente satisfecho se fidelice y se convierta en un embajador de la marca.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
		</p>  
	</div>
  </div>
</div>

{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/altaproducto.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}

<div class="row">
  <div class="col-12 col-md6">
    <div class="card">
      <div class="card-body">
        <h2>Agregar Producto</h2>
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form }}
          <div class="d-flex justify-content-center">
            <input type="reset" value="Cancelar" class="btn btn-secondary">
            <input type="submit" value="Guardar" class="btn btn-secondary">   
          </div>
        </form>     
      </div>
    </div>
  </div>
</div>      

{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/buscarproducto.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}

<h2 class="text-faded">Listado de Productos "item buscado" {{buscar}}. Total productos {{cantidadproductos}}</h2>
<div class="container">
  {% for un_producto in buscarproductos %}
  <div class="row">
    <div class="col-md-1">
      <img src="{{ un_producto.imagen.url }}" width="75%" height="75%">
    </div>
    <div class="col-md-6">
      <a href="{% url 'detalleproducto' un_producto.id %}" class="link">- {{un_producto.titulo}}: {{un_producto.descripcion}}</a>
    </div>
  </div>  
  {% endfor %} 
</div>

{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/carrito.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}
<h2 class="text-faded">Carrito</h2>
<table class="table table-borderd" style="color: white;">
  <thead>
    <tr>
      <th colspan="4" class="text-center">
        Llena el Carrito ;)
      </th>
    </tr>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Suma</th>
      <th>Precio</th>
    </tr>
  </thead>


<tbody>
  {% if request.session.carrito.items %}
    {% for key, value in request.session.carrito.items %}
      <tr class="text-center">
        <td align="left">{{ value.titulo }}</td>
        <td align="left">{{ value.cantidad }}</td>
        <td align="left">
          <a href="{% url 'carrito:agregar_producto' value.producto_id %}" class="btn btn-sm btn-warning">+</a> | 
          <a href="{% url 'carrito:restar_producto' value.producto_id %}" class="btn btn-sm btn-warning">-</a>
        </td>
        <td>$ {{ value.precio }}</td>
      </tr>
    {% endfor %}
  {% else %}
    <tr>
      <td colspan="3"></td>
      <div class="alert alert-danger text-center">
        Sin productos
      </div>
    </tr>
  {% endif %}
</tbody>

<tfoot>
  <tr align="right">
    <td align="right">
      Total: {{ importe_total_carrito }}
    </td>
  </tr>
</tfoot>
</table>
{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/categoria.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}

<h2 class="text-faded">Productos de la categoria {{categoriafiltro.descripcion}}</h2>
<div class="container">
    {% for un_producto in productosfiltro %}
    <div class="row">
      <div class="col-md-1">
        <img src="{{ un_producto.imagen.url }}" width="75%" height="75%">
      </div>
      <div class="col-md-6">
        <a href="{% url 'detalleproducto' un_producto.id %}" class="link">- {{un_producto.titulo}}: {{un_producto.descripcion}}</a>
        <a href="{% url 'detalleproducto' un_producto.id %}" class="link">$ {{un_producto.precio}}</a>
      </div>
    </div>  
    {% endfor %} 
</div>

{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/contacto.html

{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}

<h1 class="text-faded">Contactenos</h1>
<div class="container">
  <div class="row">
    <div class="col">
      <p class="text-faded">
        <form action="/contacto/" method="POST">
        {% csrf_token %}
        <p class="text-faded">Asunto: <input type="text" name="asunto"></p>
        <p class="text-faded">EMail: <input type="text" name="email"></p>
        <p class="text-faded">Mensaje: <textarea name="mensaje" rows="15" cols="45"></textarea></p>
        <p><input type="submit" value="Enviar"></p>
      </form>
    </p>  
  </div>
  </div>
</div>


{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/detalleproducto.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}

<div class="container">
	<h2 align="center" class="text-faded">Detalle del Producto {{ detalleproducto.titulo }}</h2>
	<div class="row">
		<div class="col-md-4">
			<div class="card" style="width: 75%; height: 75%;">
				<img src="{{detalleproducto.imagen.url}}" class="card-img-top" height="75%" width="75%">
			</div>
		</div>
		<div class="col-md-4" style="color: white">
			<div class="row">
				{{detalleproducto.descripcion}}
			</div>
			<div class="row">
				<div class="col-md-4" style="color: white">
					$ {{detalleproducto.precio}}
				</div>
				<div class="col-md-4">
					<a href="{% url 'carrito:agregar_producto' detalleproducto.id %}" class="btn btn-outline-warning float-end">Agregar al carrito</a>
				<!--
					<form name="FormBuscarProducto" class="d-flex" action="" method="post">
            		{% csrf_token %}
            		<button class="btn btn-outline-warning float-end" type="submit">Agregar al carrito</button>
          			</form>
          		-->
				</div>
			</div>
		</div>
		
	</div>
</div>

	
{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/home.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}
<h2 class="text-faded">Ultimos productos ingresados</h2>
<!--  -->
 <div class="container">
  <div class="row">
    {% for un_producto in primeros_tres_productos %}
    <div class="col-md-4" align="center">
      <div class="card" style="width: 75%; height: 75%;">
        <img src="{{un_producto.imagen.url}}" class="card-img-top" height="50%" width="50%">
        <!--<img src="{% static 'JAGUARETEKAA/img/ecommerce.png' %}" class="card-img-top">
         <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{post.imagen.url}}" alt="" style="width:50%;"> -->
        <div class="card-body">
          <h5 class="card-title">{{ un_producto.titulo }}</h5>
          <p class="card-text text-truncate">{{ un_producto.descripcion }}</p>
          <!-- <p align="center"><a href="{% url 'detalleproducto' un_producto.id %}" class="btn btn-warning float-center" role="button" data-bs-toggle="button">Ver</a></p> -->
          <div class="card-footer">
              <form name="FormBuscarProducto" class="d-flex" action="{% url 'detalleproducto' un_producto.id %}" method="post">
              {% csrf_token %}
              <button class="btn btn-outline-warning float-center" type="submit">Ver</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<div class="container">
    {% for resto_producto in resto_productos %}
    <div class="row">
      <div class="col-md-1">
        <img src="{{ resto_producto.imagen.url }}" width="75%" height="75%">
      </div>
      <div class="col-md-6">
        <a href="{% url 'detalleproducto' resto_producto.id %}" class="link">- {{resto_producto.titulo}}: {{resto_producto.descripcion}}</a>
      </div>
    </div>  
    {% endfor %} 
</div>
{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/layout.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <!-- Styles -->
    <link href="{% static 'JAGUARETEKAA/css/estilos.css' %}" rel="stylesheet">

</head>

<body>
  <!-- ENCABEZADO -->
  <div class="bg-warning clearfix">
    <div class="container">
      <div class="row">
        <div class="col">
          <img src="{% static 'JAGUARETEKAA/img/logo.jpeg' %}">
        </div>
        <div class="col">       
          <a  href="{% url 'carrito' %}"class="btn btn-warning float-end">Carrito</a> 
          <a  href="{% url 'registro' %}"class="btn btn-warning float-end">Registro</a>  
          {% if user.is_authenticated %}
            <!-- <a href="#">{{ user.username }}</a> -->
            <a href="#">{{ user.username }}</a>
            <a href="{% url 'logout' %}" class="btn btn-warning float-end">Cerrar sesión</a>
          {% else %}
            <a href="{% url 'login' %}" class="btn btn-warning float-end">Login</a>
          {% endif %}
        </div>        
      </div>
    </div>
  </div>

  <!-- MENU  -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categorías
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for una_categoria in categorias %}
              <li><a class="dropdown-item" href="{% url 'categoria' una_categoria.id %}">{{una_categoria.descripcion}}</a></li>
            {% endfor %}  

            <!-- {% for un_producto in productos %}
              {{productos.categorias.all}}
              {% for una_categoria in categorias %}
                <li><a class="dropdown-item" href="#">{{ una_categoria.descripcion }}</a></li>
              {% endfor %}
            {% endfor %} -->
        
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/acercade">Acerca de</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/contacto">Contacto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/altaproducto">Nuevo producto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/listaproductos">Productos</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'buscarproducto' %}" method="get">
        {% csrf_token %}
        <input name="buscar" class="form-control me-2" type="search" placeholder="Buscar" aria-label="Buscar">
        <button class="btn btn-outline-warning btn-sm" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>

  <!--  CONTENIDO VARIABLAE -->

    {% block body %}

    {% endblock %}

    <!-- PIE DE PAGINA -->
    <div class="bg-warning">
      <footer class="footer text-faded text-center py-5">
        <div class="container">
          <p class="m-0 mbt">
            <a href="" class="link">JAGUARETEKAA SAA</a> ·
            <a href="" class="link">Política de privacidad</a> ·
            <a href="" class="link">Aviso legal</a> ·
          </p>
          <p class="m-0 mbt1">&copy; E-Commerce MMXXI</p>
        </div>
    </footer>
    </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

JAGUARETEKAA/templates/JAGUARETEKAA/listaproductos.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}
<h2 class="text-faded">Listado de Productos</h2>

<table class="table table-striped table-hover table-responsive-sm">
  {% for un_producto in listaproductos %}
  <tr>
    <td><img src="{{ un_producto.imagen.url }}" width="50%" height="50%"></td>
    <td><a href="{% url 'modificarproducto' un_producto.id %}" class="link">- {{un_producto.titulo}}: {{un_producto.descripcion}}</a></td>
    <td><a href="{% url 'modificarproducto' un_producto.id %}" class="link">$ {{un_producto.precio}}</a></td>
    <td><a href="{% url 'modificarproducto' un_producto.id %}" class="btn btn-outline-warning btn-sm">Actualizar</a></td>
    <td><a href="{% url 'eliminarproducto' un_producto.id %}" class="btn btn-danger btn-sm">Eliminar</a></td>
  </tr>
  {% endfor %} 
</table>
{% endblock %}

JAGUARETEKAA/templates/JAGUARETEKAA/modificarproducto.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}

<div class="row">
  <div class="col-12 col-md6">
    <div class="card">
      <div class="card-body">
        <h2>Actualizar Producto</h2>
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form }}
          <div class="d-flex justify-content-center">
            <input type="reset" value="Cancelar" class="btn btn-secondary">
            <input type="submit" value="Actualizar" class="btn btn-secondary">   
          </div>
        </form>     
      </div>
    </div>
  </div>
</div>      

{% endblock %}

carrito/templates/CARRITO/carrito.html
{% extends "JAGUARETEKAA/layout.html" %}
{% load static %}

{% block body %}
<h2>Carrito</h2>
<table class="table table-borderd" style="color: white;">
  <thead>
    <tr>
      <th colspan="3" class="text-center">
        Llena el Carrito ;)
      </th>
    </tr>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Suma</th>
    </tr>
  </thead>


<tbody>
  {% if request.session.carrito.items %}
    {% for key, value in request.session.carrito.items %}
      <tr class="text-center">
        <td>{{ value.titulo }}</td>
        <td>{{ value.cantidad }}</td>
        <td>
          <a href="{% url 'carrito:agregar_producto' value.producto_id %}" class="btn btn-sm btn-warning">+</a>
        </td>
      
        <td>
          <a href="{% url 'carrito:restar_producto' value.producto_id %}" class="btn btn-sm btn-warning">-</a>
        </td>
      
      
        
        <td>{{ value.precio }}</td>
      </tr>
    {% endfor %}
  {% else %}
    <tr>
      <td colspan="3"></td>
      <div class="alert alert-danger text-center">
        Sin productos
      </div>
    </tr>
  {% endif %}
</tbody>

<tfoot>
  <tr>
    <td colspan="3">
      Total: {{ importe_total_carrito }}
    </td>
  </tr>
</tfoot>
</table>
{% endblock %}